#!/usr/bin/env node

var path = process.argv[2];

if (!path) {
  throw Error('Need socket path');
}

var net = require('net');
var sock = net.connect(path);
 
process.stdin.pipe(sock);
sock.pipe(process.stdout);
 
sock.on('connect', function () {
  process.stdin.setRawMode(true);
});
 
sock.on('close', function done () {
  console.log('Goodbye.');
  process.stdin.setRawMode(false);
  sock.removeListener('close', done);
  process.exit();
});
 
// process.stdin.on('end', function () {
//   sock.destroy();
// });
 
process.stdin.on('data', function (b) {
  if (b.length === 1 && b[0] === 4) {
    process.stdin.emit('end');
  }
});